root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "main"
  cmd = "just build"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go", "output.css"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "templ", "css", "js"]
  include_file = []
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  pre_cmd = []
  post_cmd = ["rm main"]
  rerun = true
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[proxy]
  proxy_port = 7331
  app_port = 8080
  enabled = true

